//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprzetKomputerowy.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class KategoriaZestawu
    {
        public int IdKategoriZestawu { get; set; }
        public string NazwaKategoriZestawu { get; set; }
    }
}
