//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprzetKomputerowy.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lokalizacja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lokalizacja()
        {
            this.Komputery = new HashSet<Komputery>();
            this.Urzadzenia = new HashSet<Urzadzenia>();
            this.Zestawy = new HashSet<Zestawy>();
        }
    
        public int IdLokalizacji { get; set; }
        public string NazwaLokalizacji { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komputery> Komputery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urzadzenia> Urzadzenia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zestawy> Zestawy { get; set; }
    }
}
