//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprzetKomputerowy.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podzespoly
    {
        public int idPodZespolu { get; set; }
        public string NazwaPodzespolu { get; set; }
        public Nullable<int> Ilosc { get; set; }
        public string NrSeryjny { get; set; }
        public string Status { get; set; }
    }
}
