//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprzetKomputerowy.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SprzetKomputerowyEntities1 : DbContext
    {
        public SprzetKomputerowyEntities1()
            : base("name=SprzetKomputerowyEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dzialy> Dzialy { get; set; }
        public virtual DbSet<KategoriaZestawu> KategoriaZestawu { get; set; }
        public virtual DbSet<KlasyfikacjaKomputera> KlasyfikacjaKomputera { get; set; }
        public virtual DbSet<KlasyfikacjaUrzadzenia> KlasyfikacjaUrzadzenia { get; set; }
        public virtual DbSet<Komputery> Komputery { get; set; }
        public virtual DbSet<Lokalizacja> Lokalizacja { get; set; }
        public virtual DbSet<Osoby> Osoby { get; set; }
        public virtual DbSet<Podzespoly> Podzespoly { get; set; }
        public virtual DbSet<StanTechniczny> StanTechniczny { get; set; }
        public virtual DbSet<Urzadzenia> Urzadzenia { get; set; }
        public virtual DbSet<UrzadzeniaWeWy> UrzadzeniaWeWy { get; set; }
        public virtual DbSet<Zestawy> Zestawy { get; set; }
    }
}
