//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprzetKomputerowy.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urzadzenia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urzadzenia()
        {
            this.Zestawy = new HashSet<Zestawy>();
        }
    
        public int IdUrzadzenia { get; set; }
        public string NrEwidencyjny { get; set; }
        public string Producent { get; set; }
        public Nullable<int> IdKlasyfikacji { get; set; }
        public string NrSeryjny { get; set; }
        public Nullable<System.DateTime> DataProdukcji { get; set; }
        public Nullable<int> IDKomputera { get; set; }
        public Nullable<int> idOsoby { get; set; }
        public Nullable<bool> CzyAktywny { get; set; }
        public string Status { get; set; }
        public Nullable<int> IdLokalizacji { get; set; }
        public Nullable<int> IdStanuTechnicznego { get; set; }
        public string NazwaUrzadzenia { get; set; }
    
        public virtual KlasyfikacjaUrzadzenia KlasyfikacjaUrzadzenia { get; set; }
        public virtual Komputery Komputery { get; set; }
        public virtual Lokalizacja Lokalizacja { get; set; }
        public virtual Osoby Osoby { get; set; }
        public virtual StanTechniczny StanTechniczny { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zestawy> Zestawy { get; set; }
    }
}
