//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprzetKomputerowy.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zestawy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zestawy()
        {
            this.Osoby = new HashSet<Osoby>();
        }
    
        public int IdZestawu { get; set; }
        public Nullable<int> IdUrzadzenia { get; set; }
        public Nullable<int> IdKomputera { get; set; }
        public string Status { get; set; }
        public string NazwaKategori { get; set; }
        public string NrEwidencji { get; set; }
        public Nullable<int> IdOsoby { get; set; }
        public Nullable<int> IdLokalizacji { get; set; }
    
        public virtual Komputery Komputery { get; set; }
        public virtual Komputery Komputery1 { get; set; }
        public virtual Lokalizacja Lokalizacja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Osoby> Osoby { get; set; }
        public virtual Osoby Osoby1 { get; set; }
        public virtual Urzadzenia Urzadzenia { get; set; }
    }
}
